FROM jenkins/jenkins:lts

COPY vars/executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
# COPY https.pem /var/lib/jenkins/cert
# COPY https.key /var/lib/jenkins/pk

# ENV JENKINS_SLAVE_AGENT_PORT 50001
# ENV JENKINS_OPTS --httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk
# EXPOSE 8083
